name: math_pdf_generator
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.3.9
  pdf: ^3.10.7
  printing: ^5.11.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true
  
  assets:
  - assets/images/logo.jpeg

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/images/ic_launcher.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

# To update
# dart run flutter_native_splash:create
flutter_native_splash:
# Lars Telephon ist alt
  color: "#000000"
  android: true
  android_12:
    color: "#000000"
    image: assets/images/ic_launcher.png