name: cube_roller
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  cubixd: ^0.1.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/larsvogel.png
    - assets/images/kiranvogelnerlich.jpeg
    - assets/images/avatar.png
    - assets/images/jennifernerlich.jpg

